In [1]:
# Write a Python program to count the number of consonants in a given string.

def countConsonants(text):
    vowels = 'aeiou';
    consonants = 0;
    for i in text:
        if i not in vowels:
            consonants += 1;
            
    return consonants;
    
print(countConsonants('learning'));

5

In [2]:
# Find the Factorial of a Number

# 1*2*3*4*5

def findFactorial(n):
    result = 1;
    for i in range(1, n+1):
        result *= i;
        
    return result;
    
print(findFactorial(5));

120

In [ ]:
# Fibonacci Sequence up to N terms

def findFibbonachiResult(n):
    result = [0,1];
    for i in range(1, n):
        result.append(result[len(result) - 1] + result[len(result) - 2])
    return result;
    
print(findFibbonachiResult(5));

[0, 1, 1, 2, 3, 5]

In [8]:
import numpy as np;
import pandas as pd;

np.random.seed(10)

df = pd.DataFrame({
    "employee_id": range(1, 501),
    "experience_years": np.random.randint(0, 20, 500),
    "salary": np.random.randint(20000, 150000, 500),
    "performance_rating": np.random.randint(1, 6, 500),
    "department": np.random.choice(["IT", "HR", "Sales", "Finance"], 500)
})

df.head()

   employee_id  experience_years  salary  performance_rating department
0            1                 9   62081                   5    Finance
1            2                 4  120202                   5         IT
2            3                15  109651                   3    Finance
3            4                 0   70175                   2         HR
4            5                17   59493                   2    Finance

In [9]:
df.tail()

     employee_id  experience_years  salary  performance_rating department
495          496                 4   31399                   2         IT
496          497                 2   37467                   2    Finance
497          498                15   22203                   5      Sales
498          499                 9   40389                   3         IT
499          500                 7   27820                   5      Sales

In [10]:
df[df['salary'] > 20000]

     employee_id  experience_years  salary  performance_rating department
0              1                 9   62081                   5    Finance
1              2                 4  120202                   5         IT
2              3                15  109651                   3    Finance
3              4                 0   70175                   2         HR
4              5                17   59493                   2    Finance
..           ...               ...     ...                 ...        ...
495          496                 4   31399                   2         IT
496          497                 2   37467                   2    Finance
497          498                15   22203                   5      Sales
498          499                 9   40389                   3         IT
499          500                 7   27820                   5      Sales

[500 rows x 5 columns]

In [11]:
df[df['department'] == 'IT']

     employee_id  experience_years  salary  performance_rating department
1              2                 4  120202                   5         IT
6              7                17   57578                   5         IT
24            25                19   37864                   5         IT
27            28                13   94355                   1         IT
29            30                13   63702                   2         IT
..           ...               ...     ...                 ...        ...
483          484                 0   95916                   2         IT
489          490                17   71607                   4         IT
493          494                15  134886                   3         IT
495          496                 4   31399                   2         IT
498          499                 9   40389                   3         IT

[126 rows x 5 columns]

In [12]:
df[df['employee_id'] > 480]

     employee_id  experience_years  salary  performance_rating department
480          481                14  149927                   2         HR
481          482                 5   72407                   5      Sales
482          483                 3  140827                   2    Finance
483          484                 0   95916                   2         IT
484          485                15   55795                   3      Sales
485          486                15  138934                   3      Sales
486          487                 2  127244                   5      Sales
487          488                 0   24311                   4      Sales
488          489                 3  115333                   2      Sales
489          490                17   71607                   4         IT
490          491                 9  145615                   2         HR
491          492                 0  109593                   5         HR
492          493                 0   68762                   3         HR
493          494                15  134886                   3         IT
494          495                18  120829                   4      Sales
495          496                 4   31399                   2         IT
496          497                 2   37467                   2    Finance
497          498                15   22203                   5      Sales
498          499                 9   40389                   3         IT
499          500                 7   27820                   5      Sales

In [13]:
df[df['department'] == None]

Empty DataFrame
Columns: [employee_id, experience_years, salary, performance_rating, department]
Index: []

In [6]:
exampleList = [1,2,3,4];
result = list(map(lambda x: x * 2, exampleList))
print(result)

[2, 4, 6, 8]