In [ ]:
# 1. Importing Pandas

import pandas as pd

# 2. Load Data

df=pd.read_csv('data.csv') # Load CSV
df = pd.read_excel('data/data.xlsx') # Load Excel

In [3]:
import numpy as np
np.random.seed(1)
rows = 200

df = pd.DataFrame({
    "PassengerId": np.arange(1, rows + 1),
    "Name": np.random.choice(["Mr. John", "Mrs. Anna", "Miss Emma", "Dr. Smith"], rows),
    "Age": np.random.choice(np.append(np.random.randint(1, 80, 180), [np.nan]*20), rows),
    "Sex": np.random.choice(["male", "female"], rows),
    "Pclass": np.random.choice([1, 2, 3], rows),
    "Fare": np.round(np.random.uniform(10, 500, rows), 2)
})

# 3. View Data

print(df.head());

   PassengerId       Name   Age     Sex  Pclass    Fare
0            1  Mrs. Anna  40.0    male       2  461.14
1            2  Dr. Smith   NaN    male       1  333.43
2            3   Mr. John  75.0    male       1  348.14
3            4   Mr. John  63.0  female       2   92.36
4            5  Dr. Smith  39.0  female       1  346.02

In [33]:
print(df.tail());

     PassengerId       Name   Age     Sex  Pclass    Fare
195          196  Miss Emma  40.0    male       2  136.23
196          197  Dr. Smith  33.0  female       1  300.03
197          198  Mrs. Anna  75.0    male       3   53.22
198          199  Mrs. Anna   NaN    male       2  431.91
199          200  Miss Emma  33.0    male       3   45.51

In [34]:
print(df.sample());

     PassengerId      Name   Age   Sex  Pclass    Fare
128          129  Mr. John  18.0  male       3  338.25

In [35]:
# 4. Inspect Structure
print(df.shape)

(200, 6)

In [36]:
print(df.columns)

Index(['PassengerId', 'Name', 'Age', 'Sex', 'Pclass', 'Fare'], dtype='object')

In [37]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Name         200 non-null    object
 2   Age          182 non-null    float64
 3   Sex          200 non-null    object
 4   Pclass       200 non-null    int64
 5   Fare         200 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 9.5+ KB
None

In [38]:
print(df.describe())

       PassengerId         Age      Pclass        Fare
count   200.000000  182.000000  200.000000  200.000000
mean    100.500000   43.318681    2.035000  251.249700
std      57.879185   22.078153    0.804369  146.847353
min       1.000000    1.000000    1.000000   11.250000
25%      50.750000   25.250000    1.000000  115.550000
50%     100.500000   41.000000    2.000000  265.430000
75%     150.250000   63.000000    3.000000  371.432500
max     200.000000   79.000000    3.000000  493.680000

In [6]:
# 5. Handling Missing Data

print(df.isnull().sum())

PassengerId     0
Name            0
Age            18
Sex             0
Pclass          0
Fare            0
dtype: int64

In [7]:
print(df.dropna(inplace=True))

None

In [8]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

/tmp/ipykernel_1134/1809399462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [12]:
# 6. Removing Duplicates

df.duplicated().sum()

np.int64(0)

In [13]:
print(df.drop_duplicates(inplace=True));

None

In [56]:
# 7. Selecting Columns
print(df['Name']);

0      Mrs. Anna
2       Mr. John
3       Mr. John
4      Dr. Smith
5      Mrs. Anna
         ...
194     Mr. John
195    Miss Emma
196    Dr. Smith
197    Mrs. Anna
199    Miss Emma
Name: Name, Length: 182, dtype: object

In [58]:
print(df[['Name', 'Age']]);

          Name   Age
0    Mrs. Anna  40.0
2     Mr. John  75.0
3     Mr. John  63.0
4    Dr. Smith  39.0
5    Mrs. Anna  26.0
..         ...   ...
194   Mr. John  53.0
195  Miss Emma  40.0
196  Dr. Smith  33.0
197  Mrs. Anna  75.0
199  Miss Emma  33.0

[182 rows x 2 columns]

In [59]:
# 8. Filtering Rows
df[df['Age'] > 30]

     PassengerId       Name   Age     Sex  Pclass    Fare
0              1  Mrs. Anna  40.0    male       2  461.14
2              3   Mr. John  75.0    male       1  348.14
3              4   Mr. John  63.0  female       2   92.36
4              5  Dr. Smith  39.0  female       1  346.02
6              7  Dr. Smith  55.0    male       2  330.93
..           ...        ...   ...     ...     ...     ...
194          195   Mr. John  53.0    male       3   40.73
195          196  Miss Emma  40.0    male       2  136.23
196          197  Dr. Smith  33.0  female       1  300.03
197          198  Mrs. Anna  75.0    male       3   53.22
199          200  Miss Emma  33.0    male       3   45.51

[122 rows x 6 columns]

In [60]:
df[df['Sex'] == 'female']

     PassengerId       Name   Age     Sex  Pclass    Fare
3              4   Mr. John  63.0  female       2   92.36
4              5  Dr. Smith  39.0  female       1  346.02
5              6  Mrs. Anna  26.0  female       2  304.88
8              9  Dr. Smith  29.0  female       3   44.05
10            11   Mr. John  77.0  female       3  247.52
..           ...        ...   ...     ...     ...     ...
183          184  Miss Emma  22.0  female       3   81.70
184          185  Miss Emma  45.0  female       1  213.40
190          191  Miss Emma  68.0  female       1  367.68
191          192  Miss Emma  78.0  female       3   12.94
196          197  Dr. Smith  33.0  female       1  300.03

[92 rows x 6 columns]

In [62]:
df[(df['Age'] > 30) & (df['Sex'] == 'female')]

     PassengerId       Name   Age     Sex  Pclass    Fare
3              4   Mr. John  63.0  female       2   92.36
4              5  Dr. Smith  39.0  female       1  346.02
10            11   Mr. John  77.0  female       3  247.52
21            22  Mrs. Anna  63.0  female       1  171.12
22            23  Miss Emma  36.0  female       2  178.59
..           ...        ...   ...     ...     ...     ...
182          183  Dr. Smith  37.0  female       3   57.42
184          185  Miss Emma  45.0  female       1  213.40
190          191  Miss Emma  68.0  female       1  367.68
191          192  Miss Emma  78.0  female       3   12.94
196          197  Dr. Smith  33.0  female       1  300.03

[65 rows x 6 columns]

In [65]:
# 9. Sorting Data
df.sort_values(by='Age', ascending=True)

     PassengerId       Name   Age     Sex  Pclass    Fare
9             10   Mr. John   1.0    male       1  242.18
38            39   Mr. John   1.0  female       2  238.26
103          104  Miss Emma   1.0    male       2  475.48
160          161  Dr. Smith   1.0  female       3  272.83
156          157  Miss Emma   4.0  female       3  330.73
..           ...        ...   ...     ...     ...     ...
144          145   Mr. John  78.0  female       3  431.38
140          141  Dr. Smith  79.0  female       2  313.47
153          154  Mrs. Anna  79.0    male       3  374.59
169          170   Mr. John  79.0    male       1   16.86
176          177  Miss Emma  79.0  female       3   80.42

[182 rows x 6 columns]

In [66]:
df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

     PassengerId       Name   Age     Sex  Pclass    Fare
56            57  Dr. Smith  23.0  female       1  490.57
162          163  Mrs. Anna  42.0  female       1  470.27
34            35  Mrs. Anna   4.0    male       1  463.46
130          131  Mrs. Anna  78.0    male       1  459.84
51            52  Mrs. Anna  15.0    male       1  451.13
..           ...        ...   ...     ...     ...     ...
194          195   Mr. John  53.0    male       3   40.73
23            24   Mr. John  68.0  female       3   33.26
145          146  Dr. Smith  29.0    male       3   15.21
191          192  Miss Emma  78.0  female       3   12.94
168          169   Mr. John  45.0  female       3   11.25

[182 rows x 6 columns]

In [18]:
# 10. Creating New Columns

df['UniqueId'] = df['PassengerId']  + df['Age'] + 1
print(df.head())

   PassengerId       Name   Age     Sex  Pclass    Fare  UniqueId
0            1  Mrs. Anna  40.0    male       2  461.14      42.0
2            3   Mr. John  75.0    male       1  348.14      79.0
3            4   Mr. John  63.0  female       2   92.36      68.0
4            5  Dr. Smith  39.0  female       1  346.02      45.0
5            6  Mrs. Anna  26.0  female       2  304.88      33.0

In [ ]:
# 11. Dropping Columns or Rows

df.drop('UniqueId', axis=1, inplace=True);
print(df.head())

   PassengerId       Name   Age     Sex  Pclass    Fare
0            1  Mrs. Anna  40.0    male       2  461.14
2            3   Mr. John  75.0    male       1  348.14
3            4   Mr. John  63.0  female       2   92.36
4            5  Dr. Smith  39.0  female       1  346.02
5            6  Mrs. Anna  26.0  female       2  304.88

In [22]:
df.drop([0,2], axis=0, inplace=True);
print(df.head())

   PassengerId       Name   Age     Sex  Pclass    Fare
3            4   Mr. John  63.0  female       2   92.36
4            5  Dr. Smith  39.0  female       1  346.02
5            6  Mrs. Anna  26.0  female       2  304.88
6            7  Dr. Smith  55.0    male       2  330.93
7            8  Mrs. Anna  71.0    male       3  263.67

In [24]:
# 12. Renaming Columns

df.rename(columns={'Fare': 'FareRate'}, inplace=True);
print(df.head())

   PassengerId       Name   Age     Sex  Pclass  FareRate
3            4   Mr. John  63.0  female       2     92.36
4            5  Dr. Smith  39.0  female       1    346.02
5            6  Mrs. Anna  26.0  female       2    304.88
6            7  Dr. Smith  55.0    male       2    330.93
7            8  Mrs. Anna  71.0    male       3    263.67

In [26]:
# 13. Value Counts & Unique

print(df['Sex'].value_counts());

Sex
female    92
male      88
Name: count, dtype: int64

In [27]:
print(df['Name'].unique())

['Mr. John' 'Dr. Smith' 'Mrs. Anna' 'Miss Emma']

In [28]:
print(df['Name'].nunique())

4

In [ ]:
# 14. Grouping and Aggregation

3      False
4      False
5      False
6      False
7      False
       ...
194    False
195    False
196    False
197    False
199    False
Name: Name, Length: 180, dtype: bool

In [34]:
print(df.groupby('Pclass')['FareRate'].mean())

Pclass
1    238.893750
2    285.149683
3    226.580820
Name: FareRate, dtype: float64

In [35]:
print(df.groupby('Sex')['FareRate'].sum())

Sex
female    22356.72
male      22807.19
Name: FareRate, dtype: float64

In [36]:
print(df.groupby(['Pclass', 'Sex'])['Age'].median())

Pclass  Sex
1       female    45.0
        male      33.0
2       female    36.0
        male      43.0
3       female    41.0
        male      40.0
Name: Age, dtype: float64

In [38]:
# 15. Aggregating Multiple Columns

# group by pclass and find the mean and min of age and mean and max of fare.
print(df.groupby('Pclass').agg({
    'Age': ['mean', 'min'],
    'FareRate': ['mean', 'max']
}))

              Age         FareRate
             mean  min        mean     max
Pclass
1       41.982143  1.0  238.893750  490.57
2       42.603175  1.0  285.149683  481.81
3       44.819672  1.0  226.580820  489.08

In [43]:
# 16. Apply Custom Functions

df['AgeSquared'] = df['Age'].apply(lambda x: x**2);
print(df)

     PassengerId       Name   Age     Sex  Pclass  FareRate  AgeSquared
3              4   Mr. John  63.0  female       2     92.36      3969.0
4              5  Dr. Smith  39.0  female       1    346.02      1521.0
5              6  Mrs. Anna  26.0  female       2    304.88       676.0
6              7  Dr. Smith  55.0    male       2    330.93      3025.0
7              8  Mrs. Anna  71.0    male       3    263.67      5041.0
..           ...        ...   ...     ...     ...       ...         ...
194          195   Mr. John  53.0    male       3     40.73      2809.0
195          196  Miss Emma  40.0    male       2    136.23      1600.0
196          197  Dr. Smith  33.0  female       1    300.03      1089.0
197          198  Mrs. Anna  75.0    male       3     53.22      5625.0
199          200  Miss Emma  33.0    male       3     45.51      1089.0

[180 rows x 7 columns]

In [47]:
# 17. String Operations
print(df['Name'].str.lower())

3       mr. john
4      dr. smith
5      mrs. anna
6      dr. smith
7      mrs. anna
         ...
194     mr. john
195    miss emma
196    dr. smith
197    mrs. anna
199    miss emma
Name: Name, Length: 180, dtype: object

In [51]:
print(df['Name'].str.contains('Mrs'))

3      False
4      False
5       True
6      False
7       True
       ...
194    False
195    False
196    False
197     True
199    False
Name: Name, Length: 180, dtype: bool

In [4]:
# 18. Mapping & Replacing Values

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
print(df.head())

   PassengerId       Name   Age  Sex  Pclass    Fare
0            1  Mrs. Anna  40.0    0       2  461.14
1            2  Dr. Smith   NaN    0       1  333.43
2            3   Mr. John  75.0    0       1  348.14
3            4   Mr. John  63.0    1       2   92.36
4            5  Dr. Smith  39.0    1       1  346.02

In [13]:
df['Name'].replace({'Mrs. Anna': "Mrs. Ann", 'Mr. John': 'Johnny'}, inplace=True);
print(df.head())

   PassengerId       Name   Age  Sex  Pclass    Fare
0            1   Mrs. Ann  40.0    0       2  461.14
1            2  Dr. Smith   NaN    0       1  333.43
2            3     Johnny  75.0    0       1  348.14
3            4     Johnny  63.0    1       2   92.36
4            5  Dr. Smith  39.0    1       1  346.02

In [16]:
# 19. Combining Columns (concatenation)

df['fullname'] = df['Name'] + ' (' + df['Sex'].astype(str) + ')'
print(df.head());

   PassengerId       Name   Age  Sex  Pclass    Fare       fullname
0            1   Mrs. Ann  40.0    0       2  461.14   Mrs. Ann (0)
1            2  Dr. Smith   NaN    0       1  333.43  Dr. Smith (0)
2            3     Johnny  75.0    0       1  348.14     Johnny (0)
3            4     Johnny  63.0    1       2   92.36     Johnny (1)
4            5  Dr. Smith  39.0    1       1  346.02  Dr. Smith (1)